//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceId { get; set; }
        public int RoomId { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public string Term { get; set; }
        public string Month { get; set; }
        public string Day { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Deposit { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
