//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessLog
    {
        public int LogId { get; set; }
        public string LogType { get; set; }
        public string LogDecription { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    
        public virtual System_Users System_Users { get; set; }
    }
}
