//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public int RoomId { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
